[LINE_CLASSIFY]
LineScore = 0.94
AngleThres = 10
HorizAngleThres = 10     
; new (used for horizontals if present)

[HEIGHT_MEAS]
InitialDistThres = 0.3
DistThres = 100.0
ValidHeightRatio = 0.001
MinValidHeightNum = 1
NSigmaCriterion = 0
MaxDBSANDist = 50

[LINE_REFINE]
Edge_Thres = 4

[SEGMENTATION]
SkyLabel = 2
BuildingLabel = 1
GroundLabel = 0

[STREET_VIEW]
CameraHeight = 2.5
HVFoV = 90
Pitch = 25 

[GROUND_TRUTH]
Exist = 0

[LINE]
VERT_TOL_DEG = 10
HORIZ_TOL_DEG = 10       
; new: angular tolerance to horizontal VPs
MIN_SCORE = 0.0          
; optional: keep lines with score >= MIN_SCORE
